### ISSUE TITLE
"Get user data" ohne Authorisierung?

### ISSUE THREAD

**Issue by ingoboerner** [phaidra/phaidra-api#8]
In der Dokumentation ist angegeben, dass _Get user data_ nur nach  Authorisierung möglich ist:
https://github.com/phaidra/phaidra-api/wiki/Documentation#get-user-data
Es scheint aber auch zu klappen, ohne dass man den Token sendet. Kann das sein? Gilt auch zumindest für _Get name of a user_

```
curl -X GET "https://services.phaidra.univie.ac.at/api/directory/user/boernei6/name"
{"name":"Ingo Borner","status":200}
```

**Comment by RastislavHudak** [comment]
Danke fuer die Fehlermeldung. Ja, [das stimmt so](https://github.com/phaidra/phaidra-api/blob/7cee3cbb909c379eed0645cd81e4e7369451139e/PhaidraAPI.pm#L340), es steht falsch im Doku. Frueher braeuchte sich man authentifizieren (mit beliebigen u:account), deswegen steht es dort so, jetzt gehts auch ohne auth, da es sowieso nur oeffentliche daten liefert (name und email).
Werde ich im wiki nachbessern...

**Comment by RastislavHudak** [comment]
Fixed
