### ISSUE TITLE
simple search api seems not working

### ISSUE THREAD

**Issue by yurj** [phaidra/phaidra-api#91]
curl -X GET "https://services.phaidra.univie.ac.at/api/search/" -F "q=Wien"

returns nothing. Here:

curl -X GET "https://phaidra.cab.unipd.it/api/search" -F "q=test"

[2023/11/10 12:50:47] [ERROR] [16605] [error] [AwDn7XbbACJJ]
Can't locate object method "delay" via package "Mojo::IOLoop" at /usr/local/phaidra/phaidra-api/PhaidraAPI/Controller/Search.pm line 177.

Maybe upgrading to Mojolicious 9 broke this?

**Comment by giulioturetta** [comment]
Mojolicious 9 removed `Mojo::IOLoop::Delay`, cf. https://metacpan.org/dist/Mojolicious/changes#L180.

**Comment by yurj** [comment]
Solved by https://github.com/phaidra/phaidra-api/pull/92
Thanks!
